# Using Mysql version
development:
  adapter: mysql2
  database: compupack
  pool: 5
  username: root
  password: root

test:
  adapter: mysql2
  database: compupack
  pool: 5
  username: root
  password: root

production:
  adapter: mysql2
  database: compupack
  pool: 5
  username: root
  password: root
